version: "3.8"
services:
  backend:
    image: apollo-server-nexus:latest
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules

volumes:
  backend:
